<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rekening extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rekening_model');
        $this->load->model('Transaksi_model');
    } 

    /*
     * Listing of rekening
     */
    function index()
    {
        $data['rekening'] = $this->Rekening_model->get_all_rekening();
        
        $data['_view'] = 'rekening/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new rekening
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $id_pengguna = $this->session->userdata("id");
            $params = array(
				'id_pengguna' => $id_pengguna,
				'nama' => $this->input->post('nama'),
				'catatan' => $this->input->post('catatan'),
            );
            
            $rekening_id = $this->Rekening_model->add_rekening($params);
            redirect('rekening/index');
        }
        else
        {            
            $data['_view'] = 'rekening/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a rekening
     */
    function edit($id)
    {   
        // check if the rekening exists before trying to edit it
        $data['rekening'] = $this->Rekening_model->get_rekening($id);
        
        if(isset($data['rekening']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
					'catatan' => $this->input->post('catatan'),
                );

                $this->Rekening_model->update_rekening($id,$params);            
                redirect('rekening/index');
            }
            else
            {
                $data['_view'] = 'rekening/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The rekening you are trying to edit does not exist.');
    } 

    /*
     * Deleting rekening
     */
    function remove($id)
    {
        $rekening = $this->Rekening_model->get_rekening($id);

        // check if the rekening exists before trying to delete it
        if(isset($rekening['id']))
        {
            $this->Rekening_model->delete_rekening($id);
            redirect('rekening/index');
        }
        else
            show_error('The rekening you are trying to delete does not exist.');
    }

    function history($id)
    {
        $transaksi = $this->Transaksi_model->get_transaksi_per_rekening($id);
        
        $data['transaksi'] = $transaksi;
        
        $data['_view'] = 'rekening/transaksi';
        $this->load->view('layouts/main',$data);
    }
    
}
