<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pengguna_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pengguna by id
     */
    function get_pengguna($id)
    {
        $pengguna = $this->db->query("
            SELECT
                *

            FROM
                `pengguna`

            WHERE
                `id` = ?
        ",array($id))->row_array();

        return $pengguna;
    }
        
    /*
     * Get all pengguna
     */
    function get_all_pengguna()
    {
        $pengguna = $this->db->query("
            SELECT
                *

            FROM
                `pengguna`

            WHERE
                1 = 1

            ORDER BY `id` DESC
        ")->result_array();

        return $pengguna;
    }
        
    /*
     * function to add new pengguna
     */
    function add_pengguna($params)
    {
        $this->db->insert('pengguna',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pengguna
     */
    function update_pengguna($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('pengguna',$params);
    }
    
    /*
     * function to delete pengguna
     */
    function delete_pengguna($id)
    {
        return $this->db->delete('pengguna',array('id'=>$id));
    }
}
