<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rekening_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rekening by id
     */
    function get_rekening($id)
    {
        $rekening = $this->db->query("
            SELECT
                *

            FROM
                `rekening`

            WHERE
                `id` = ?
        ",array($id))->row_array();

        return $rekening;
    }
        
    /*
     * Get all rekening
     */
    function get_all_rekening()
    {
        $id_pengguna = $this->session->userdata("id");
        $rekening = $this->db->query("
            SELECT
                *

            FROM
                `rekening`

            WHERE
                id_pengguna = $id_pengguna

            ORDER BY `id` DESC
        ")->result_array();

        foreach ($rekening as $r) {
            $this->updateSaldo($r['id']);
        }

        $rekening = $this->db->query("
            SELECT
                *

            FROM
                `rekening`

            WHERE
                id_pengguna = $id_pengguna

            ORDER BY `id` DESC
        ")->result_array();

        return $rekening;
    }
        
    /*
     * function to add new rekening
     */
    function add_rekening($params)
    {
        $this->db->insert('rekening',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rekening
     */
    function update_rekening($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('rekening',$params);
    }
    
    /*
     * function to delete rekening
     */
    function delete_rekening($id)
    {
        return $this->db->delete('rekening',array('id'=>$id));
    }


    function execQuery($query){
        return $this->db->query($query);   
    }

    function getOneValue($query){
        return $this->db->query($query)->row();
    }


    function updateSaldo($rekening_id)
    {
        $querySaldoTerpakai = "
            select 
                IFNULL(sum(nominal),0) as JumlahNominal 
            from 
                transaksi t 
                inner join category c 
                    on t.id_category = c.id 
            where 
                c.jenis = 0
                and t.id_rekening = $rekening_id
            ";
        $SaldoTerpakai = $this->getOneValue($querySaldoTerpakai)->JumlahNominal;

        $querySaldoMasuk = "
            select 
                IFNULL(sum(nominal),0) as JumlahNominal 
            from 
                transaksi t 
                inner join category c 
                    on t.id_category = c.id 
            where 
                c.jenis = 1
                and t.id_rekening = $rekening_id
            ";
        $SaldoMasuk = $this->getOneValue($querySaldoMasuk)->JumlahNominal;

        $queryUpdateSaldo = "
            update 
                rekening 
            set 
                totalsaldomasuk = $SaldoMasuk,
                totalsaldokeluar = $SaldoTerpakai,
                saldosekarang = $SaldoMasuk -$SaldoTerpakai 
            where id = $rekening_id;";

        $this->execQuery($queryUpdateSaldo);
        
    }

    function getSaldo(){
        $id_pengguna = $this->session->userdata("id");
        $this->get_all_rekening(); // refress saldo

        $query = "select sum(saldosekarang) as saldosekarang from rekening where id_pengguna = $id_pengguna ;";
        $saldosekarang = $this->getOneValue($query)->saldosekarang;

        return $saldosekarang;
    }

}
