<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Transaksi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get transaksi by id
     */
    function get_transaksi($id)
    {
        $transaksi = $this->db->query("
            SELECT
                *

            FROM
                `transaksi`

            WHERE
                `id` = ?
        ",array($id))->row_array();

        return $transaksi;
    }
        
    /*
     * Get all transaksi
     */
    function get_all_transaksi()
    {
        $id_pengguna = $this->session->userdata("id");
        $transaksi = $this->db->query("
            SELECT 
                t.*, 
                c.jenis, 
                c.nama,
                r.nama as namaRekening
            FROM 
                `transaksi` t 
                inner join category c 
                    on t.id_pengguna = c.id_pengguna 
                    and c.id = t.id_category 
                inner join rekening r on r.id = t.id_rekening
            where 
                t.id_pengguna = $id_pengguna 
            ORDER by t.tanggal desc
        ")->result_array();

        return $transaksi;
    }

    function get_transaksi_per_rekening($id){
        $transaksi = $this->db->query("
            SELECT 
                t.*, 
                c.jenis, 
                c.nama,
                r.nama as namaRekening
            FROM 
                `transaksi` t 
                inner join category c 
                    on t.id_pengguna = c.id_pengguna 
                    and c.id = t.id_category 
                inner join rekening r on r.id = t.id_rekening
            where 
                r.id = $id 
            ORDER by t.tanggal desc
        ")->result_array();

        return $transaksi;
    }
        
    /*
     * function to add new transaksi
     */
    function add_transaksi($params)
    {
        $this->db->insert('transaksi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update transaksi
     */
    function update_transaksi($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('transaksi',$params);
    }
    
    /*
     * function to delete transaksi
     */
    function delete_transaksi($id)
    {
        return $this->db->delete('transaksi',array('id'=>$id));
    }

    function tampilData($query){
        return $this->db->query($query)->result_array();
    }

    function execQuery($query){
        return $this->db->query($query);   
    }

    function getOneValue($query){
        return $this->db->query($query)->row();
    }

    function updateSaldo($rekening_id)
    {
        $querySaldoTerpakai = "
            select 
                sum(nominal) as JumlahNominal 
            from 
                transaksi t 
                inner join category c 
                    on t.id_category = c.id 
            where 
                c.jenis = 0
                and t.id_rekening = $rekening_id
            ";
        $SaldoTerpakai = $this->getOneValue($querySaldoTerpakai)->JumlahNominal;

        $querySaldoMasuk = "
            select 
                sum(nominal) as JumlahNominal 
            from 
                transaksi t 
                inner join category c 
                    on t.id_category = c.id 
            where 
                c.jenis = 1
                and t.id_rekening = $rekening_id
            ";
        $SaldoMasuk = $this->getOneValue($querySaldoTerpakai)->JumlahNominal;

        $queryUpdateSaldo = "
            update 
                rekening 
            set 
                totalsaldomasuk = $SaldoMasuk,
                totalsaldokeluar = $SaldoTerpakai,
                saldosekarang = $SaldoMasuk -$SaldoTerpakai ";

        $this->execQuery($queryUpdateSaldo);
        
    }

    function totalPengeluaranBulanIni()
    {
        $id_pengguna = $this->session->userdata("id");

        $query = "
            select 
                sum(nominal) as JumlahNominal 
            from 
                transaksi t 
                inner join category c 
                    on t.id_category = c.id 
            where 
                c.jenis = 0
                and month(t.tanggal) =  month(now()) 
                and year(t.tanggal) =  year(now()) 
        ";
        $JumlahNominal = $this->getOneValue($query)->JumlahNominal;

        return $JumlahNominal;
    }


    function totalPemasukanBulanIni()
    {
        $id_pengguna = $this->session->userdata("id");

        $query = "
            select 
                sum(nominal) as JumlahNominal 
            from 
                transaksi t 
                inner join category c 
                    on t.id_category = c.id 
            where 
                c.jenis = 1
                and month(t.tanggal) =  month(now()) 
                and year(t.tanggal) =  year(now()) 
        ";
        $JumlahNominal = $this->getOneValue($query)->JumlahNominal;

        return $JumlahNominal;
    }

    

    function pengeluaranPerCategory()
    {
        $id_pengguna = $this->session->userdata("id");

        $query = "
            SELECT 
                c.id, c.nama, sum(t.nominal) as totalPemakaian
            FROM 
                `transaksi` t 
                inner join category c on c.id = t.id_category
             where 
                c.jenis = 0
                and t.id_pengguna = $id_pengguna
             GROUP by c.id
        ";

        return $this->tampilData($query);

    }

    function PemasukanPerCategory()
    {
        $id_pengguna = $this->session->userdata("id");

        $query = "
            SELECT 
                c.id, c.nama, sum(t.nominal) as totalPemakaian
            FROM 
                `transaksi` t 
                inner join category c on c.id = t.id_category
             where 
                c.jenis = 1
                and t.id_pengguna = $id_pengguna
             GROUP by c.id
        ";

        return $this->tampilData($query);
    }
}
